FROM alpine:3.6

RUN apk add --no-cache nginx-mod-http-lua nginx-mod-http-echo jq
RUN apk update
RUN apk upgrade
RUN apk add bash

# Delete default config
RUN rm -r /etc/nginx/conf.d
#RUN rm /etc/nginx/nginx.conf

# Create folder for PID file
RUN mkdir -p /run/nginx

# Add our nginx conf
#COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./printContents.sh /printContents.sh
COPY ./create_nginx_conf.sh /create_nginx_conf.sh
COPY ./run-nginx.sh /run-nginx.sh
RUN chmod +x /printContents.sh
RUN chmod +x /run-nginx.sh
RUN chmod +x /create_nginx_conf.sh

#CMD ["nginx"]
#CMD ["./run-nginx.sh"]
ENTRYPOINT ["sh","/run-nginx.sh"]
